#!/bin/bash -
set -e

rsync -a --quiet --delete --exclude=.gitignore --exclude=cache /media/psf/discographer/ ~/discographer/
mkdir -m 0755 -p ~/discographer/source/cache
exec ~/discographer/source/discographer -v -d examples
